### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by shimil2017** [voximplant/react-native-demo#14]
can you please provide the installation process completely

**Comment by YuliaGrigorieva** [comment]
Please check the updated instruction, it's now much more verbose and detailed

**Comment by shimil2017** [comment]
i ma not able to seee the update one

**Comment by YuliaGrigorieva** [comment]
Hello!

The instructions how to run the demo project: https://github.com/voximplant/react-native-demo/blob/master/README.md
The instructions how to integrate React Native Voximplant SDK: https://github.com/voximplant/react-native-voximplant/blob/master/README.md

Please let us know if you face any issues.

Best regards,
Yulia Grigorieva

**Comment by shimil2017** [comment]
Thank you Yulia Grigorieva,
for your king help
