### ISSUE TITLE
How to login?

### ISSUE THREAD

**Issue by trungbkit** [voximplant/react-native-demo#16]
I have cloned this project and built it to my Android device, but I can't login, it shows "Invalid username". Can you help me?

**Comment by YuliaGrigorieva** [comment]
Hello!

You need to create a user account and an application.
Please take a look at these tutorials:

- https://voximplant.com/docs/quickstart/10/understanding-users-applications-and-rules
- https://voximplant.com/docs/quickstart/1/your-first-voximplant-application

Best regards,
Yulia Grigorieva

**Comment by trungbkit** [comment]
thanks YuliaGrigorieva, but I still can't make a call, can you guide me?

**Comment by YuliaGrigorieva** [comment]
Hello!

Were you able to login to demo application?
Could you please provide the information about what kind of issue do you have on making a call? Do you receive CallFailed event (demo app shows a popup with call failed reason)? If so, could you please provide details (pop up message)?

Best regards,
Yulia Grigorieva

**Comment by trungbkit** [comment]
I have logged in to it. But in order to make a call, I have to input a *Number to call*. Where can I find that number?

**Comment by YuliaGrigorieva** [comment]
Could you please specify where you would like to make a call (to the demo application on another device, to a phone number, etc)?
Depends on the call desctination, you need to use different Voxengine scenarios and enter different data to the "Namber to call" field.

For example:
1. if you would like to make a sdk-to-sdk (demo-to-demo) call, you need to use VoxEngine.forwardCallToUserDirect(); scenario and input the name of another voximplant user you would like to call
2. if you would like to make a call to a phone number, you need to use VoxEngine.forwardCallToPSTN(); scenario and input the phone number to "Number to call" field.

Best regards,
Yulia Grigorieva

**Comment by selvadrew** [comment]
I've created an account and application. 

I am not sure what credentials to use to login. I keep getting "Invalid username". The links you've mentioned does not seem to include the right steps to login. Please let me know where the username and password come from.

**Comment by Rock2106** [comment]
Hi... @YuliaGrigorieva 

"user@app.account" as the login
where
"user" - the username of the user you have created
"app" - Voximplant application name that you have created
"account" - your Voximplant account name
i have tried this but i can't login ... please help me with an example

**Comment by YuliaGrigorieva** [comment]
Hello @Rock2106 ,

Have you created a Voximplant developer account, Voximplant application and Voximplant users?

Best regards,
Yulia Grigorieva

**Comment by Rock2106** [comment]
yes @YuliaGrigorieva

**Comment by YuliaGrigorieva** [comment]
Hello @Rock2106 ,

Please provide the error details, what happens after you press "login" button.

Best regards,
Yulia Grigorieva

**Comment by Rock2106** [comment]
@YuliaGrigorieva  its says invalid "username" ... i am confused that what would be my "app" and "account" name in login and "@" is also required in username?
because "app" name is very long for example : test.<Voximplant developer account user name>.Voximplant.com

**Comment by YuliaGrigorieva** [comment]
Hello @Rock2106 ,

Please take a look at the screenshot:
<img width="1201" alt="Screenshot 2019-07-12 at 15 12 48" src="https://user-images.githubusercontent.com/8545374/61127476-0e28bf80-a4b8-11e9-93fe-d7f85449f8d5.png">

app - "newapplication"
account - blured text

Please consider you should not enter ".voximplant.com" to the demo application login screen, demo app will add it itself to your input. It is implemented to minify the input on mobile devices.

Please let me know the results.

Best regards,
Yulia Grigorieva

**Comment by Rock2106** [comment]
hi @YuliaGrigorieva  Thanks a lot ... it worked ... 
i have another question that can i implement a complete chat application like whatsapp using that application as a reference ?

**Comment by YuliaGrigorieva** [comment]
Hello @Rock2106 ,

This demo application demonstrates audio and video call functionality using Voximplant React Native SDK. 

Voximplant React Native SDK have the APIs to implement message chat functionality as well, however we do not have a demo application for messaging yet.

You can use this demo app as reference for audio and video calls implementation and take a look at Voximplant React Native SDK documentation for messaging functionality: https://voximplant.com/docs/references/reactnative/voximplant/messaging

Best regards,
Yulia Grigorieva

**Comment by Rock2106** [comment]
Hello @YuliaGrigorieva ,
you just explained the scenario above that 
"if you would like to make a sdk-to-sdk (demo-to-demo) call, you need to use VoxEngine.forwardCallToUserDirect(); scenario and input the name of another voximplant user you would like to call"
VoxEngine.forwardCallToUserDirect() can you tell how to do ?

**Comment by YuliaGrigorieva** [comment]
Hello @Rock2106 ,

Please take a look at our quickstart guide for more details: https://voximplant.com/docs/references/articles/quickstart/apps-scenarios-rules-and-users

Please follow the instruction of "JavaScript cloud scenarios" and add `VoxEngine.forwardCallToUserDirect();` 1-line scenario instead of the provided one in the article.

Best regards,
Yulia Grigorieva
