### ISSUE TITLE
Call failed. Reason: Not Found

### ISSUE THREAD

**Issue by dead23angel** [voximplant/react-native-demo#18]
Installed your demo application.
It was registered on your site.
I created an application and two users.
I launched two android emulator.
Authorized in each of them under different logins (admin and Konstantin).
On behalf of Constantine I try to dial by dialing "admin", but I get a message "Call failed. Reason: Not Found"

```
04-06 14:00:38.872  3950  4865 I ReactNativeJS: Login successful Константи
04-06 14:00:47.270  3950  4865 I ReactNativeJS: calling admin
04-06 14:00:47.864  3950  4865 W ReactNativeJS: Call failed. Code 404 Reason Not Found
```

**Comment by YuliaGrigorieva** [comment]
Hello!

Please ensure that you have also created scenario and correctly setup application rules.
Please take a look at the following tutorial, especially at _'Creating VoxImplant Application, App Users, App Rule, and VoxEngine Scenario'_ part. 
https://voximplant.com/blog/voximplant-p2p-video-chat
It contains the screenshots that may help you to validate your setup.

Best regards, 
Yulia Grigorieva

**Comment by dead23angel** [comment]
@YuliaGrigorieva thanks!

Не знал что можно было по русски, но сюда по вашему имени и фамилии можно было и так.
В общем то да, я забыл создать сценарий и правило, создав их все заработало. Вы просто спасли меня.
