### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by swaroopa94** [voximplant/react-native-demo#2]
Hi,
 I Just installed your module and run in my xcode , but the build is failed showing an error like this:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_VoxImplant", referenced from:
      objc-class-ref in libVoxImplant.a(VoxImplantModule.o)
      objc-class-ref in libVoxImplant.a(VoxView.o)
     (maybe you meant: _OBJC_CLASS_$_VoxImplantModule, _OBJC_CLASS_$_VoxImplantRendererViewManager , _OBJC_CLASS_$_VoxImplantRendererView )
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have done everything mentioned in the description but it did not work.
so, Please help me with the solution.....

Thank you

**Comment by swaroopa94** [comment]
please respond quickly...

**Comment by YuliaGrigorieva** [comment]
Supported in the latest SDK version
