### ISSUE TITLE
what's the username and password ne？

### ISSUE THREAD

**Issue by Cenyol** [voximplant/react-native-demo#21]
I install the demo just having not the login info, and I can't find the place to regist. plz

**Comment by YuliaGrigorieva** [comment]
Hello!

You need first register here: https://voximplant.com/sign-up#dosignin

To login to demo application and make calls, you need to create users, application, rules and scenarios.
Please take a look at our quick start guide: https://voximplant.com/docs/quickstart/category/voximplant-basics

The following link may also be useful for you:
https://voximplant.com/blog/voximplant-p2p-video-chat

Best regards,
Yulia Grigorieva
