### ISSUE TITLE
Build does not work

### ISSUE THREAD

**Issue by ricsam** [voximplant/react-native-demo#23]
Followed the exact steps described in README.

### Error:
```
Make sure you're running a packager server or have included a .jsbundle file in your application bundle.
```

Can you include a package-lock.json or yarn.lock file in the repository to ensure that the same packages are used?

### System
```
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.10.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257
```

**Comment by YuliaGrigorieva** [comment]
Hello!

You probably need to start the webserver via "react-native start" command in Terminal. Run "react-native start" from the root project directory.

Also please ensure that there is no other webservers running for other projects at the moment. In case of any, please stop them.

Let me know if it resolves your issue.

Best regards,
Yulia Grigorieva

**Comment by ricsam** [comment]
@YuliaGrigorieva Hi! Thanks for the fast response. I tried running the webserver with `react-native start` but nothing. I've also restarted the computer without any luck. 
And I've also run `rm -rf node_modules && yarn install && cd ios && rm -rf Pods && pod install`

**Comment by YuliaGrigorieva** [comment]
Hello!

I have updated the project to use RN 0.56 and committed `package-lock.json` file.

I also observe this issue in case if `react-native start` is not run before building the project.

Please pull the latest version and follow the steps:
1. clean project
2. run `pod deintegrate` from ios folder and remove *.xcworkspace file
3. remove `node_modules`
4. run `nom install`
5. run `pod install` from ios folder
6. run `react-native start` from the project root. Ensure that dependency graph is loaded successfully
7. build and run from Xcode

Best regards,
Yulia Grigorieva

**Comment by ricsam** [comment]
Running `react-native start` before building fixed it! Thank you very much! 🏅
