### ISSUE TITLE
Can't Retrieve displayName() of Called User

### ISSUE THREAD

**Issue by ralfisalhon** [voximplant/react-native-demo#25]
Hello!

Quick question, here is my scenario:
`require(Modules.ASR);
VoxEngine.forwardCallToUser(function(call1, call2){
  call1.record({stereo: true, transcribe: true, labels: [call1.displayName(), call2.displayName()], language: ASRLanguage.ENGLISH_US})
});`

However, here is my transcription: 
> user 00:00:00 - 00:00:01 : hello
> rifat.salhon@tufts.edu 00:00:01 - 00:00:03 : hello my friend

As you can see here, I expected "user" to be the person I called, however no matter what I do, call2.displayName() returns "user".

Any thoughts? Thanks!
Ralfi

**Comment by YuliaGrigorieva** [comment]
Hello!

Thank you for your report!
It seems to be an issue on our side, we are investigating it and will get back to you soon.

Best regards,
Yulia Grigorieva

**Comment by ralfisalhon** [comment]
This is fixed now, thank you!
