### ISSUE TITLE
Can't Retrieve "RecordType" Struct From HTTP API

### ISSUE THREAD

**Issue by ahkaneti** [voximplant/react-native-demo#26]
Hello!

I am using the VoxImplant HTTP API from https://voximplant.com/docs/references/httpapi
I am trying to access the "RecordType" struct for a call from https://voximplant.com/docs/references/httpapi/recordtype
Since this is a struct and not a method, I don't know what HTTP request will retrieve me this struct for a given call_id or other call identifiers. Any help would be dearly appreciated.

Thank you and Best Regards,
Aaron Kaneti

**Comment by grigoryvp** [comment]
Hello!

It's returned by https://voximplant.com/docs/references/httpapi/managing_history#getcallhistory as part of other structure

**Comment by ralfisalhon** [comment]
Hello @grigoryvp !

I have followed the getCallHistory call and successfully returned my result, however I don't seem to have a URL to the transcription in any of the JSON results. I have even followed the log file url, and the txt file for the transcription file does not seem to be there. Could you help out?

Here is a part of the returned JSON:
<img width="477" alt="screen shot 2018-07-27 at 12 45 51 pm" src="https://user-images.githubusercontent.com/16303372/43314350-5c809c74-919b-11e8-8e19-92cd6844663a.png">

And this is from the .log file that the URL is given for:
<img width="1398" alt="screen shot 2018-07-27 at 12 48 52 pm" src="https://user-images.githubusercontent.com/16303372/43314454-9f968c8a-919b-11e8-9a7b-ef96a568c6cc.png">

And that .mp3 file is the voice recording of the call. However, I was only trying to access the txt file of the transcription.

Any help is hugely appreciated!
Thanks,
Ralfi

**Comment by grigoryvp** [comment]
The easiest way is to check how our control panel, https://manage.voximplant.com/#callhistory, gets transcription result from call history. Our entire control panel is built atop of our HTTP API, so you can use it as a reference implementation and check correct calls in the "network" tab of your browser's dev toold

**Comment by ahkaneti** [comment]
Thank you !
