### ISSUE TITLE
GetCallHistory Method With Faulty Return

### ISSUE THREAD

**Issue by ralfisalhon** [voximplant/react-native-demo#27]
Hello!

I have been using the GetCallHistory method from https://voximplant.com/docs/references/httpapi/managing_history#getcallhistory

From the documentation:
> user_id: string
> The user ID list separated by the ';' symbol. If it's specified the output will contain only calls from/to any VoxImplant SDK related to the specified user.

This is exactly what I need, as I input the user_id in my API call to get the calls from AND to that user. However, with this call:
`https://api.voximplant.com/platform_api/GetCallHistory/?account_id=<acc_id>&api_key=<api_key>&user_id=<user_id>`

It only returns the calls made FROM the given user_id, and not those TO the user_id.

Any help is appreciated,
Ralfi

**Comment by grigoryvp** [comment]
Can you please contact us at support@voximplant.com and attach both cloud-side call log and /GetCallHistory result?

**Comment by ralfisalhon** [comment]
Thanks @grigoryvp, I have contacted the support team with all the requested information.
