### ISSUE TITLE
Call Failed: Not found issue - React Native

### ISSUE THREAD

**Issue by isurugajasinghe** [voximplant/react-native-demo#28]
In Demo app I configured. app open successfully and logged into app. Then I typed username inside textfield("Call to" - placeholder textfield)

Then I clicked call button , then I got the issue, as below (isurugg is username i created from manage.voximplant.com then I called to isurugg from sameera's account)

Running application "VoximplantDemo" with appParams: {"rootTag":11}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
infoLog.js:16
fx4g35sbaug:APA91bFK-Jl75fA-e7zUQmfiBsXjjs5SJyOnZfVp7GBT-R6u1CkCcKuQGzaC8IcBgzwN3FLDeIkkzw0pLuOCahKqzWz6zeV0343VvXDmVQ_-gJbFdh7O45Y2a883n0V_bP0VNT5LMmCi
PushManager.android.js:31
MainScreen: make call: isurugg, isVideo:false
MainScreen.js:83
CallManager: addCall:ViwsDYl37JfJHX8agxoA88gXOqAvK4tGNxCU
CallManager.js:42
CallScreen: ctr: callid: ViwsDYl37JfJHX8agxoA88gXOqAvK4tGNxCU, isVideoCall: false, isIncoming:  false, callState: disconnected
CallScreen.js:60
CallScreen: _onCallEndpointAdded: callid: ViwsDYl37JfJHX8agxoA88gXOqAvK4tGNxCU endpoint id: ViwsDYl37JfJHX8agxoA88gXOqAvK4tGNxCU
CallScreen.js:223

**Comment by YuliaGrigorieva** [comment]
Hello!

Please ensure that you have created a JS scenario and application rule in the Voximplant control panel.
You can use our quickstart as a reference:
https://voximplant.com/docs/references/articles/quickstart/apps-scenarios-rules-and-users

Best regards,
Yulia Grigorieva
