### ISSUE TITLE
Requiring unknown module "react-native/Libraries/Portal/Portal".If you are sure the module is there, try restarting the packager or running "npm install".

### ISSUE THREAD

**Issue by chetnadaffodil** [voximplant/react-native-demo#3]
**Portal removal for RN0.26+
https://github.com/d-a-n/react-native-modal-picker/pull/12**

![screenshot from 2016-07-18 15 01 03](https://cloud.githubusercontent.com/assets/17562095/16910912/fe2e50dc-4cf8-11e6-894e-bd04c135494e.png)

**Comment by aylarov** [comment]
We have removed Portal module in the latest commit, it hasn't been pushed to npm yet, since we are waiting for another few fixes on rnpm side (node-xcode).
