### ISSUE TITLE
What should happen on new notification?

### ISSUE THREAD

**Issue by ruscoder** [voximplant/react-native-demo#30]
Hello! Thank you for the demo application.

Now, I receive notifications which are just displayed as an usual push notifications. But I expected to see an incoming call screen with buttons accept/decline because it is a VoIP app.

I tried an example on Android with RN 0.56.0 and VI 1.1.1.

**Comment by YuliaGrigorieva** [comment]
Hello!

This demo application shows a notification in case if the screen is locked or application is in the background on android. After notification click, it will show the incoming call screen with buttons to accept/decline call.

The main goal of this demo application is to show the key possibilities of our React Native SDK and how to work with it. 

The way how incoming call notification is displayed for the application is up to the application developers and should be based on the product design and concept. 
As we have a demo application, we tried to make this functionality the easiest way to avoid code complexity.

Best regards,
Yulia Grigorieva

**Comment by ruscoder** [comment]
Ok, thanks!
