### ISSUE TITLE
Getting error: Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).

### ISSUE THREAD

**Issue by VishalVema** [voximplant/react-native-demo#31]
`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'VoximplantDemo'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html`

**Comment by YuliaGrigorieva** [comment]
Hello!

Thank you for reporting the issue.

Could you please provide more information:
1. Android studio version on your machine
2. Do you build the project in Android Studio or using `react-native run-android`

Best regards,
Yulia Grigorieva

**Comment by YuliaGrigorieva** [comment]
Hello, @VishalVema !

We have just merged a fix for this issue to master branch (d9505938)
Could you please pull the latest changes and try building again?

Please let us know the results.

Best regards,
Yulia Grigorieva

**Comment by VishalVema** [comment]
Okay i will give it a try
