### ISSUE TITLE
com.voximlpant error 480

### ISSUE THREAD

**Issue by sukhdeep540** [voximplant/react-native-demo#34]
I have 2 users 
test1
test2

When test1 makes a call and test2 is not connected(Application closed).

I receives the below error.
Call failed:
The operation couldn't be complete.
com.voximplant error 480

**Scenario Used:-**
VoxEngine.forwardCallToUserDirect();

I am assuming when the other user is not connected I can send a notification to the user "test2".
But on the user test1 side, it gives error very quickly. There is not timeout.
So is there any feasibility of timeout functionality.

**Comment by deftsoftiphone** [comment]
Hello Yulia

I am also facing similar kind of issue with the SDK.

The solution you shared  will send push notification.

How it will prevent call failed event?

**When ever the user got disconnected, the other user will receive**
Call failed:
The operation couldn't be complete.
com.voximplant error 480

And the call failed.

How this can be managed?

**Comment by YuliaGrigorieva** [comment]
Hello!

If the scenario contains `require(Modules.PushService);`, VoxEngine will manage timeouts automatically and these timeouts are not configurable. 
VoxEngine will wait user login event for 20 seconds after a push notification is sent. If the user is not logged in during this time, the call will be failed. If the user logged in, he will receive incoming call event and he will have the same time to answer a call as for general call.

Best regards,
Yulia Grigorieva

**Comment by vijendrapatidar** [comment]
Username invalid error is getting 
how to call api and change my url.

**Comment by YuliaGrigorieva** [comment]
Hello, @vijendrapatidar !

Could you please provide more details about your issue?

Best regards,
Yulia Grigorieva
