### ISSUE TITLE
Unable to  initiate a call when app enters foreground frommbackground.

### ISSUE THREAD

**Issue by sukhdeep540** [voximplant/react-native-demo#35]
Use Case:-
1. App Login
2. Take app in background
3. Get app in foreground.
4. Initiate call
5. You will get undefined error in Catch

I debuged the native code and found that call object(VICall) is nil, only when user enters foregorund from background and connection established again.

if (_client) {
        VICallSettings *callSettings = [[VICallSettings alloc] init];
        callSettings.customData = customData;
        callSettings.extraHeaders = headers;
        callSettings.videoFlags = [VIVideoFlags videoFlagsWithReceiveVideo:[[videoFlags valueForKey:@"receiveVideo"] boolValue]
                                                                 sendVideo:[[videoFlags valueForKey:@"sendVideo"] boolValue]];
        callSettings.preferredVideoCodec = videoCodec;
        `VICall *call = [_client call:user settings:callSettings];`
        if (call) {
            if (setupCallKit) {
                [[VIAudioManager sharedAudioManager] callKitConfigureAudioSession:nil];
            }
            [CallManager addCall:call];
            [call start];
            callback(@[call.callId]);
        } else {
            callback(@[[NSNull null]]);
        }
    } else {
        callback(@[[NSNull null]]);
    }

**Comment by YuliaGrigorieva** [comment]
Hello!

Thank you for reaching out!

VICall object may be null, if the Client is not connected and logged in. We will improve the native implementation to provide the error with details of the call creation fail.

According to your scenario, when the application on iOS enters the background, the connection to the Voximplant Cloud is closed and you should receive ClientEvents.ConnectionClosed event. When the application enter the foreground, the connection is not established automatically by SDK, the application should re-establish the connection and re-login the user. 

>  only when user enters foregorund from background and connection established again.

Could you please check that you also re-login user after entering the foreground?

I have just checked your scenario on the demo application. After entering the foreground, the application goes to login screen. If you reproduce the issue on demo application, could you please provide more details, so we could improve the demo application behaviour?

Best regards,
Yulia Grigorieva
