### ISSUE TITLE
Call decline

### ISSUE THREAD

**Issue by renanpupin** [voximplant/react-native-demo#36]
After follow the setup instructions I got the automatic "Decline" when tried to call.

Is it necessary configure the push notifications to make the example work?

![image](https://user-images.githubusercontent.com/8743530/49664164-35a63e00-fa38-11e8-879e-58af8db4bfb3.png)
![image](https://user-images.githubusercontent.com/8743530/49664199-540c3980-fa38-11e8-95b0-15111902536c.png)

**Comment by YuliaGrigorieva** [comment]
Hello!

Thank you for reaching out!

You don't need to set up push notifications to make calls when the application is foreground.

The demo application is implemented the way that only one active call can be at the moment. It is not the restriction of the Voximplant SDK, but only of the demo application to simplify the demo application code. If the application receives a new call while another call is active, it declines a new call.

If you make a call and receive this error, please check your VoxEngine scenario and ensure that it does not create 2 calls instead of one call. 

Best regards,
Yulia Grigorieva

**Comment by renanpupin** [comment]
I have tested with 2 iOS simulators because I can't login at android.
There is no call in progress when I tried to call another simulator.

**Comment by YuliaGrigorieva** [comment]
Hello!

Please provide your VoxEngine scenario for further issue investigation.

You can also create a separate issue for login issue on android, so we could help you to resolve it.

Best regards,
Yulia Grigorieva

**Comment by renanpupin** [comment]
Sure, I followed the tutorial and created the scenario "User2User".
Let me know if there is something else that I can help.

**Comment by panchalsanket** [comment]
@YuliaGrigorieva  

> Hello!
> 
> if you use one of scenarios provided in [this article](https://voximplant.com/blog/voximplant-p2p-video-chat), the call should be established successfully.
> 
> According to the error you receive in the demo application, I see the following possible reasons:
> 
> 1. your VoxEngine scenario is empty
> 2. your VoxEngine scenario process the call twice
> 
> So, to get the root cause of the issue you can either provide your scenario in the comment or provide the call session logs from [the Voximplant Control Panel](https://manage.voximplant.com) -> Calls ->Calls -> Find a call with the issue -> Download log -> Attach it
> 
> Best regards,
> Yulia Grigorieva

[
[2019_10_02_125653_ac79352d053592f3.1570021013.5350491_203.195.121.227.log](https://github.com/voximplant/react-native-demo/files/3681197/2019_10_02_125653_ac79352d053592f3.1570021013.5350491_203.195.121.227.log)
](url)

**Comment by YuliaGrigorieva** [comment]
Hello @panchalsanket ,

The logs provided contains error `name = Call.Failed ;  reason = User not found ; `. It means that the user you are calling to, is not created (does not exist) in the Voximplant application.

Please also note that according to the logs provided your scenario initiates 2 calls. Please check your Voximplant application configuration.

Best regards,
Yulia Grigorieva
