### ISSUE TITLE
how to receive call when app closed ?  

### ISSUE THREAD

**Issue by dinhtrumdieu** [voximplant/react-native-demo#37]
Any documents related to this issue.  Thank you !

**Comment by dinhtrumdieu** [comment]
> Any documents related to this issue. Thank you !

**Comment by saikiranoptisol** [comment]
why you have closed this. did you find any solution

**Comment by YuliaGrigorieva** [comment]
@saikiranoptisol, you need to use push notifications to receive calls when the appplication is closed.

Please take a look at these articles abou push notification setup:
1. android - https://voximplant.com/docs/references/androidsdk/push-notifications-for-android
2. ios - https://voximplant.com/docs/references/iossdk/push-notifications-for-ios

Best regards,
Yulia Grigorieva
