### ISSUE TITLE
Error in Ios installation of plugin

### ISSUE THREAD

**Issue by tusharnetset** [voximplant/react-native-demo#39]
Hi
I am trying to add voximplant npm in react native ios but I am getting this error again and again
"dyld: Library not loaded: @rpath/CocoaLumberjack.framework/CocoaLumberjack
Referenced from: /Users/netset/Library/Developer/CoreSimulator/Devices/617330EF-27D9-42C7-82EE-1DC99A381F05/data/Containers/Bundle/Application/4FACB3CA-A6D8-4E94-BB35-0F863BDAF536/Levelz.app/Frameworks/VoxImplant.framework/VoxImplant
Reason: image not found"

Can you please help me out into this issue?

**Comment by YuliaGrigorieva** [comment]
The issue duplicates https://github.com/voximplant/react-native-voximplant/issues/63

Closing this one
