### ISSUE TITLE
No getPackages( ) method in MainActivity.java

### ISSUE THREAD

**Issue by gamebusterz** [voximplant/react-native-demo#4]
The Getting Started Guide states that: 'Add `new VoxImplantReactPackage()` to the list returned by the `getPackages() `method '. But there is no` getPackages()` method in '`MainActivity.java`'

**Comment by aylarov** [comment]
Yes, this changed in RN 29+, will update the installation instructions accordingly

**Comment by aylarov** [comment]
Fixed with https://github.com/voximplant/react-native-demo/commit/91e7d0fda233188a3d9c707b9f6086b2baa136fe
