### ISSUE TITLE
Error: VIForegroundService: Foreground service failed to stop

### ISSUE THREAD

**Issue by izaa** [voximplant/react-native-demo#40]
Hi,
how to handle this ? 

C:\proj\node_modules\react-native\Libraries\YellowBox\YellowBox.js:67 Possible Unhandled Promise Rejection (id: 0):
Error: VIForegroundService: Foreground service failed to stop
Error: VIForegroundService: Foreground service failed to stop

**Comment by YuliaGrigorieva** [comment]
Hello!

Thank you for reporting the issue!

Could you please provide detailed steps to reproduce the issue?

Best regards,
Yulia Grigorieva

**Comment by YuliaGrigorieva** [comment]
I have found the issue reproducible when the call is disconnected before being established and fixed it.

Closing the issue for now, if you observe the issue in other cases, please reopen it.

Best regards,
Yulia Grigorieva
