### ISSUE TITLE
iOS cannot see any notification

### ISSUE THREAD

**Issue by izaa** [voximplant/react-native-demo#41]
Hi,

		"react": "16.6.0-alpha.8af6728",
		"react-native": "0.57.8",
		"react-native-voximplant": "1.4.0",

all calls come trough ok if the app is open. If the app is put to background, can see no notifications at all when call arrives.

I have installed both  Apple Push Notification service SSL and VOIP certificates in VOX management console. Btw, do I need both if only receiving video calls?

From the management console, I can see the call details. it says following:
`
2019-02-07 08:39:43 send push wakeup message:{"addr" : "188.42.37.36:5090" , "callid" : "5ehgC7N8SwCOsaYIrPbWH-alsv9XCEy7hqWUPumeFGA" , "display_name" : "Name" , "sessionid" : "a66e39ff144dc1cc.1549528783.1559738_188.42.37.36" , "userid" : "thRZTstgxtKSdA8nE@my.app.voximplant.com"}
`

and later

`
2019-02-07 08:39:43 Sent event to JS onPhoneEvent with params [{code = 480 ;  headers = {} ;  id = pSmjhaJ0TMG-bTFdRhWYVtgMYBhq2kC9meLUY1oblOc ;  name = Call.Failed ;  reason = User offline ;  } ;  ]

`
My Scenario

```
require(Modules.PushService)
VoxEngine.addEventListener(AppEvents.CallAlerting, function (e) {
  	trace(e);
    var newCall = VoxEngine.callUser(e.destination, e.callerid, e.displayName, e.headers, true);
    VoxEngine.easyProcess(e.call, newCall);
});
```

When the app is background, i cannot see anything from the xcode log nor rn debugger. What should I try next?

P.s. why there is only pushkit integrated to appdelegate.m, no callkit at all? 

Thanks!

**Comment by YuliaGrigorieva** [comment]
Hello!

When the application enters background on iOS, the connection to the Voximplant Cloud is closed. To receive calls when the application is in the background or closed, you need to use push notifications.

If you need to receive incoming calls, you need only VoIP Services push certificate, i.e. Apple Push Notification service SSL is not required.

According to the logs provided, it seems that you have already modified your VoxEngine scenario by adding `require(Modules.PushService);`. The next step I recommend you look at the call session logs for the line: `push wakeup result: ... ` and ensure that the result of sending push notification is success.

> When the api is background, i cannot see anything from the xcode log files.

If you do not stop the application / Xcode run, you should be able to see the logs in Xcode output.

> why there is only pushkit integrated to appdelegate.m, no callkit at all?

Demo application has both PushKit and CallKit integration. PushKit is the framework to handle push notifications, CallKit is the framework to display common call UI. So CallKit is not required to handle push notifications. In demo application we use 'react-native-callkit' module v1.3.4, according to this module documentation it is not required to change AppDelegate to handle incoming calls.

Do you reproduce this issue with demo application or with your own?
 
Best regards
Yulia Grigorieva

**Comment by izaa** [comment]
Hi! Thanks for the reply.

no wakeup result messages.Yes this is your demo app but I've  modified the UI. I havent touched the pushmanager-files yet. 

```
Executing JS command: CallUser with params [{id = BlrV2mQiQvOuBNrmQeTfIXuvf3ryZEN3ta1noRqhi5M ;  } ;  {audioLevelExtension = NULL ;  callerid = LScNThZaZc4Q9RQoo ;  displayName = Name ;  headers = {VI-Authenticated-Caller = LScNThZaZc4Q9RQoo ;  VI-Browser = voxmobile ;  VI-Client-Device = WebRTC ;  VI-Client-IP = 82.181.240.244 ;  VI-Client-Type = user ;  VI-ClientVersion = 2.8.1 ;  X-o-h-l = rKgi9urJaCFegBx8L-DZEurFZnqAWeqnq4i-A ;  } ;  maxVideoBitrate = NULL ;  mixStreams = NULL ;  proxyid = GiuhZuTsQBeKv0tnWHYXtY1EzwtFskc2uZDYBEeCsE8 ;  scheme = NULL ;  sendWakeup = true ;  username = thRZTstgxtKSdA8nE ;  video = true ;  } ;  ]

 send push wakeup message:{"addr" : "188.42.37.36:5090" , "callid" : "GiuhZuTsQBeKv0tnWHYXtY1EzwtFskc2uZDYBEeCsE8" , "display_name" : "Name" , "sessionid" : "a191e12945a0b396.1549530842.1605577_188.42.37.36" , "userid" : "thRZTstgxtKSdA8nE@zapp.interque.voximplant.com"}
```

**Comment by YuliaGrigorieva** [comment]
Hello!

It is very strange that you don't have `push wakeup result:` log in the call session logs.

Please reach out to us at support@voximplant.com and provide the call session logs for further investigation.

Best regards,
Yulia Grigorieva
