### ISSUE TITLE
Cant able to run the demo

### ISSUE THREAD

**Issue by saikiranoptisol** [voximplant/react-native-demo#42]
I have followed the steps that are given to run theis demo app. evertything works fine.  Once the app is got installed in ios it is showing exception as 

dyld: Library not loaded: @rpath/CocoaLumberjack.framework/CocoaLumberjack
  Referenced from: /private/var/containers/Bundle/Application/E26B0502-56CA-408A-8037-8A3D84376501/VoximplantDemo.app/Frameworks/VoxImplant.framework/VoxImplant
  Reason: image not found

I cant bale to find solution for this in the issues. Please help

**Comment by YuliaGrigorieva** [comment]
Hello!

Could you please specify the CocoaPods version you are using?

Best regards,
Yulia Grigorieva

**Comment by izaa** [comment]
@saikiranoptisol i did pod deintegrate and pod install, then it worked.

**Comment by chrise86** [comment]
@saikiranoptisol did you manage to resolve the issue? I'm getting this when trying to use the library in my own project.
