### ISSUE TITLE
google services issue

### ISSUE THREAD

**Issue by kashkama** [voximplant/react-native-demo#43]
Hey, I'm trying to run your demo with react native android. After following every instruction on your README on setting everything up I get an error when I run react-native run-android. 
```
Task :app:processDebugGoogleServices FAILED
```

**Comment by YuliaGrigorieva** [comment]
Hello!

Do you build the application via `react-native run-android` or via Android Studio?
Could you please provide full build log?

Best regards,
Yulia Grigorieva
