### ISSUE TITLE
User/password ?

### ISSUE THREAD

**Issue by alexalghisi** [voximplant/react-native-demo#48]
How ca I create a new user ?

I tried to login with my gmail account but nothing happened

<img width="392" alt="Screenshot 2019-05-31 at 09 15 22" src="https://user-images.githubusercontent.com/10101138/58685651-25d33b00-8385-11e9-99d0-2c2cbc4f577f.png">

**Comment by YuliaGrigorieva** [comment]
Hello!

First, you need to create a Voximplant account (https://manage.voximplant.com/auth/sign_up)
Then, you need to create a Voximplant application and users, VoxEngine scenario for calls and setup routing for calls.

Please check our quickstart: https://voximplant.com/docs/references/articles/quickstart
Please also take a look at this tutorial: https://voximplant.com/blog/voximplant-p2p-video-chat. Here you can find an example of VoxEngine scenario for audio/video calls between SDKs.

Best regards,
Yulia Grigorieva
