### ISSUE TITLE
Error: Accessing 'ReactNative.createClass' from 'react-native' instead of 'react'

### ISSUE THREAD

**Issue by gamebusterz** [voximplant/react-native-demo#5]
I have the Latest clone of the repositories and all other tools and I've followed the getting started Guide as it is. But still I'm getting this error:
**Seems you're trying to access '`ReactNative.createClass`' from the '`react-native`' package. Perhaps you meant to access '`ReactNative.createClass`' from the '`react`' package instead ?**

I've searched the complete code and the only such use of `from 'react-native;` is in the `throwOnWrongReactAPI.js` as a string which is responsible for printing this error. 
Also, there is no usage such as **`ReactNative.createClass`** in the code.

**Comment by aylarov** [comment]
Fixed with https://github.com/voximplant/react-native-demo/commit/99cfd2f75d077baeb2bbdc33a7c7ce3bd8a8495e

**Comment by gamebusterz** [comment]
@aylarov Thanks, that fixed that issue. Although now when I run `npm start` in another terminal window and then reload the app (all of this after running `react-native run-android`). All I see is a never-ending `**Establishing Connection**` . Any hints ?

**Comment by aylarov** [comment]
Just try one more time, it can happen in emulator sometimes
