### ISSUE TITLE
User to user audio/video call

### ISSUE THREAD

**Issue by alexei-sevrukov-topx** [voximplant/react-native-demo#51]
Hi, I'm trying make user to user call, but I saw that there are functions which are not used like `receiveVideo`, `_onCallConnected` and others. So how it should be implemented?
In account I added scenario:
```VoxEngine.addEventListener(AppEvents.CallAlerting, (e) => {
  const newCall = VoxEngine.callUserDirect(
    e.call, 
    e.destination,
    e.callerid,
    e.displayName,
    null
  );
  VoxEngine.easyProcess(e.call, newCall, ()=>{}, true);
});

**Comment by YuliaGrigorieva** [comment]
Hello @alexei-sevrukov-topx ,

I suppose you mean this piece of code:
https://github.com/voximplant/react-native-demo/blob/5b4ff8b75d056af9274b74845616d9844c7d929b/src/screens/CallScreen.js#L168-L175

This method is not used in this demo (there is no button on the call screen to start receiving video during a call) and was added to the project just to show how it may be implemented. 

If you would like to use this method, you can take this implementation and assign it to a button or any other code like `sendVideo` method:
https://github.com/voximplant/react-native-demo/blob/5b4ff8b75d056af9274b74845616d9844c7d929b/src/screens/CallScreen.js#L397-L403

Your scenario looks okey ( probably you have not added the first line with CallAlerting). Please consider that you should also set up the routing in your Voximplant application to make calls work.

Please also note that the scenario is running in the Voximplant Cloud and describes how the calls should be processed. But the Voximplant React Native SDK is used in a RN application.

Best regards,
Yulia Grigorieva

**Comment by alexei-sevrukov-topx** [comment]
Good day @YuliaGrigorieva I managed to make audio/video from one user to another. So problem was in scenario. I changed all previous code to this one line and it started working. Thanks
```
VoxEngine.callUserDirect()
