### ISSUE TITLE
React Native 0.60 ios xcode cannot run, only show blank screen

### ISSUE THREAD

**Issue by robert589** [voximplant/react-native-demo#52]
> If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-netinfo
> 2019-09-30 14:05:30.502 [error][tid:com.facebook.react.JavaScript] Module AppRegistry is not a registered callable module (calling runApplication)
> 2019-09-30 14:05:30.501737+0800 VoximplantDemo[25613:164397] Module AppRegistry is not a registered callable module (calling runApplication)
> 2019-09-30 14:05:30.502728+0800 VoximplantDemo[25613:164383] [] nw_socket_handle_socket_event [C3.1:1] Socket SO_ERROR [61: Connection refused]
> 2019-09-30 14:05:30.505510+0800 VoximplantDemo[25613:164383] [] nw_socket_handle_socket_event [C3.2:1] Socket SO_ERROR [61: Connection refused]
> 2019-09-30 14:05:30.508477+0800 VoximplantDemo[25613:164386] [] nw_connection_get_connected_socket [C3] Client called nw_connection_get_connected_socket on unconnected nw_connection
> 2019-09-30 14:05:30.567 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Module AppRegistry is not a registered callable module (calling runApplication)
> 2019-09-30 14:05:30.566815+0800 VoximplantDemo[25613:164393] Unhandled JS Exception: Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by YuliaGrigorieva** [comment]
Hello @robert589 ,

Could you please provide the steps that lead to this behaviour?
Have you run `pod install`?
Have you opened `VoximplantDemo.xcworkspace` file to build the project?

Best regards,
Yulia Grigorieva

**Comment by robert589** [comment]
Hi, i have solved the issue. it turns out this demo has postinstall in the package.json that we have to include
