### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by nkbeldar** [voximplant/react-native-demo#54]
I can Login this app but alert message generate username incorrect

**Comment by YuliaGrigorieva** [comment]
Hello @nkbeldar ,

Please ensure that you have created a Voximplant developer account and set up the Voximplant application (users, scenarios and rules).

You should log in to the demo application with the Voximplant users.

You can create them manually in the [Voximplant Control Panel](https://manage.voximplant.com/)
OR
You can use "SDK tutorial" template from our marketplace:
![market](https://user-images.githubusercontent.com/8545374/66670276-0e288f00-ec62-11e9-8b6e-fa784f6bedab.png)

Best regards,
Yulia Grigorieva
