### ISSUE TITLE
Incoming call fails on (only)IOS with code: 10010, reason: "Internal error

### ISSUE THREAD

**Issue by hurali97** [voximplant/react-native-demo#59]
Hi, first of all the voximplant sdk has been a great help altogether but I have been testing calls on android devices only and that works completely fine and making calls with ios devices works fine too but the issue pops up on ios devices on incoming calls. The calls cannot be connected and fails with this error log:
failed.. {code: 10010, reason: "Internal error", name: "Failed", headers: {…}, call: Call}

Any ideas on how to fix this issue?

**Comment by YuliaGrigorieva** [comment]
Hello @hurali97 !

Thank you for reaching out to us!

To investigate the issue we need full SDK logs. Please contact us at support@voximplant.com and send the full SDK logs from Xcode output.

Best regards,
Yulia Grigorieva

**Comment by maitzeth** [comment]
Hello @YuliaGrigorieva Im facing this error (Even with the react-native-demo) I dont know why this happens. 

But mine said: 

```
"headers": {
    "X-VI-Hangup-Cause": "Normal termination"
  },
  "reason": "Decline",
  "code": 603,
  "name": "Failed",
  "call": {
    "_events": [
      "VICallConnected",
      "VICallDisconnected",
      "VICallEndpointAdded",
      "VICallFailed",
      "VICallICECompleted",
      "VICallICETimeout",
      "VICallInfoReceived",
      "VICallMessageReceived",
      "VICallProgressToneStart",
      "VICallProgressToneStop",
      "VICallLocalVideoStreamAdded",
      "VICallLocalVideoStreamRemoved"
    ],
    "callId": "IySAUlxmX68eYWFsoxOJFsj3wZ1cjlHmWQZZ",
    "listeners": {
      "Connected": {},
      "Disconnected": {},
      "EndpointAdded": {},
      "Failed": {}
    }
  }
```

Everytime I try to call someone with iOS (With all the CallKeep setup)
