### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by SahilKKothari** [voximplant/react-native-demo#66]
I have cloned this project and built it to my Android device, but I can't login, it shows "Invalid Error" and then "Invalid username" popup. Can you help me?
I did created application, rules, scenario and user as well for my demoapp.

**Comment by vevnkataSukumar** [comment]
@SahilKKothari how you fixed this issue. can you please help me out to get out from this issue.

Thanks

**Comment by SahilKKothari** [comment]
Sorry for delayed response. If still you were facing issue then let me know.
