### ISSUE TITLE
Unable to view video some times

### ISSUE THREAD

**Issue by basanthalluri** [voximplant/react-native-demo#7]
Here is the log from xcode

<Warning>: startCall called while in state  0
<Warning>: Set remote native renderer 0x1b047b70
<Warning>: Set preview native renderer 0x1b0dd5c0
<Notice>: (Error) PS: Authentication failed. Code: 401.
<Notice>: (Error) PS: MSPublishStreamsProtocol - 1102602980 Failed authentication. Error: __NSCFError:
 Domain  : streamsProtocolCoreErrorDomain
 Code    : 2
 Desc    : The Photo Stream server has rejected the user’s login credentials.
 UserInfo: {
     NSLocalizedDescription = "The Photo Stream server has rejected the user\U2019s login credentials.";
 }
<Notice>: (Error) PS: MSPublisher - 1102602980 Found authentication error. Will try again later...
 <Notice>: (Error) mstreamd: Encountered authentication error for personID 1102602980.
 <Notice>: (Note ) mstreamd: Ignoring authentication failure as we are already handling a previous authentication error.
 <Notice>: (Note ) mstreamd: Monitoring for external power.
 <Notice>: (Note ) mstreamd: We are waiting for the user to refresh their iCloud passcode. Not quitting.
 <Notice>: (Note ) PS: MSPublisher - 1102602980 Sending metadata...
<Notice>: (Error) PS: Authentication failed. Code: 401.
<Notice>: (Error) PS: MSPublishStreamsProtocol - 1102602980 Failed authentication. Error: __NSCFError:
 Domain  : streamsProtocolCoreErrorDomain

I am getting the authenitcation error some time. 

Thanks
Basanth

**Comment by aylarov** [comment]
Basanth, I have no idea what Photo Stream server is , it's not related to Voximplant.

**Comment by swaroopa94** [comment]
Hie I am using your module i too have the same issue that the call is being connected but the view is taking much time to load especially the remote view.
Sometimes i am getting the answer model lately.
Can you tell me what to do to solve this.
In my log its showing like this:

:Called remote function __ping with params []
: Called local function __pong with params []
: Called remote function __ping with params []
: Called local function __pong with params []
: Called remote function __ping with params []
: Called local function __pong with params []
: Called remote function __ping with params []
: Called local function __pong with params []
: Called remote function __ping with params []
: Called local function __pong with params []
: Called remote function __ping with params []
: Called local function __pong with params []
: Called remote function __ping with params []
: Called local function __pong with params []
: Called remote function __ping with params []
: Called local function __pong with params []

**Comment by aylarov** [comment]
Remote view shows video when first video keyframe arrives, if keyframe lost during the transmission it takes some time before it's retransmitted. Are you using P2P call scenario?

**Comment by swaroopa94** [comment]
Yes I am Using Peer to Peer Scenario

**Comment by anishtr4** [comment]
@swaroopa94  Did  you figure out the issue ?

@aylarov any idea ?

**Comment by anishtr4** [comment]
@aylarov  when I am using web application to connect to my mobile app(peer to peer). Sometimes the video not showing in mobile and web but the call is getting connected properly. Please let me know if there is any solution. If this works we are planning to use your service for our commercial purpose.

Also please do let me know fi there is any way to call without per to per from Websdk to mobile.app.

**Comment by YuliaGrigorieva** [comment]
Fixed in the latest SDK version
