### ISSUE TITLE
Cannot able to login in the demo App

### ISSUE THREAD

**Issue by renishdeveloper** [voximplant/react-native-demo#72]
I cannot able to login with the Username added in the Voximplant control panel.

**Comment by YuliaGrigorieva** [comment]
Hello @renishdeveloper ,

Please ensure that you enter the login credentials in the following format:

login: `user@application.account`
where:
`user` - Voximplant user name in the Voximplant application
`application` - Voximplant application created in the Voximplant Control Panel
`account` - Your Voximplant account name

password: the password created/set for this Voximplant user in the Voximplant application

Best regards,
Yulia Grigorieva
