### ISSUE TITLE
Call failed

### ISSUE THREAD

**Issue by wandonye** [voximplant/react-native-demo#8]
I installed the demo to a real iPhone, logged in with testuser2.
From a simulator, I logged in the app with testuser1.
From either side I cannot call the other. Below is the log I found from the website control panel:

> 2016-10-11 04:09:57 Loading scenario User2User
> 2016-10-11 04:09:57 Sent event to JS onPhoneEvent with params [{accessURL = http://173.0.146.133:12092/request/1270970dd93c09ed.1476158997.93876_173.0.146.133/bc51ea434830e53f ;  accountId = 687614 ;  applicationId = 1372747 ;  initiatorCountry = US ;  logURL = http://www-us-02-133.voximplant.com/logs/2016/10/11/040957_1270970dd93c09ed.1476158997.93876_173.0.146.133.log ;  name = Application.Started ;  sessionId = 18151735 ;  userId = 81189 ;  } ;  ]
> 2016-10-11 04:09:57 Sent event to JS onPhoneEvent with params [{callerid = testuser2 ;  destination = testuser1 ;  displayName = Test User 2 ;  fromURI = sip:testuser2@videochat.colang.voximplant.com ;  headers = {VI-Authenticated-Caller = testuser2 ;  VI-Client-Device = WebRTC ;  VI-Client-IP = 71.90.100.239 ;  VI-Client-Type = user ;  X-DirectCall = true ;  } ;  id = 2d2d852434a40c62.1476158997.93875 ;  name = Application.CallAlerting ;  toURI = sip:testuser1@videochat.colang.voximplant.com ;  } ;  ]
> 2016-10-11 04:09:57 Executing JS command: CallUserDirect with params [{id = e3cxn0B6TIy20m9FixQb8C2n1xj7nEC9sOw_glEIh2M ;  } ;  {callerid = Test User 2 ;  displayName = {VI-Authenticated-Caller = testuser2 ;  VI-Client-Device = WebRTC ;  VI-Client-IP = 71.90.100.239 ;  VI-Client-Type = user ;  X-DirectCall = true ;  } ;  headers = NULL ;  incomingCall = 2d2d852434a40c62.1476158997.93875 ;  username = testuser1 ;  } ;  ]
> 2016-10-11 04:09:57 Executing JS command: SendMediaBetween with params [{id1 = 2d2d852434a40c62.1476158997.93875 ;  id2 = e3cxn0B6TIy20m9FixQb8C2n1xj7nEC9sOw_glEIh2M ;  } ;  ]
> 2016-10-11 04:09:58 Sent event to JS onPhoneEvent with params [{code = 500 ;  headers = {} ;  id = e3cxn0B6TIy20m9FixQb8C2n1xj7nEC9sOw_glEIh2M ;  name = Call.Failed ;  reason = Can't create dialog ;  } ;  ]
> 2016-10-11 04:09:58 Terminating (onClose)
> 2016-10-11 04:09:58 Executing JS command: close with params [void ;  ]
> 2016-10-11 04:09:58 Session terminated

**Comment by aylarov** [comment]
It happens if you specify callerid in a wrong format, it can't have whitespaces
