### ISSUE TITLE
Payment Required

### ISSUE THREAD

**Issue by shayan555** [voximplant/react-native-demo#82]
How to set X-DirectCall header for p2p in react-native-demo

**Comment by YuliaGrigorieva** [comment]
Hello @shayan555 ,

Please use the following VoxEngine scenario for p2p calls:
```
VoxEngine.addEventListener(AppEvents.CallAlerting, (e) => {
  const newCall = VoxEngine.callUserDirect(
    e.call, 
    e.destination,
    e.callerid,
    e.displayName,
    e.headers
  );
  VoxEngine.easyProcess(e.call, newCall, ()=>{}, true);
});
```

Setting `X-DirectCall` header is no more required.

Please consider that p2p calls are free, but you can be charged for TURN usage. Please take a look at [pricing](https://voximplant.com/pricing)

Best regards,
Yulia Grigorieva

**Comment by shayan555** [comment]
great thanks lot.
